# Generated by Django 4.0 on 2021-12-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccount',
            table='user_account',
        ),
    ]
